/**
 * Created by Phan on 12/16/2016.
 */
module.exports = {
    login:{
        loginGuest:{
            X:576,
            Y:720
        },
        loginScene:{
            X:1108,
            Y:632
        },
        signUpScene:{
            X:1007,
            Y:806
        },
        loginEmailInput:{
            X:1413,
            Y:462
        },
        loginFacebookBtn:{
            X:918,
            Y:393
        },
        loginFacebookEmailInput:{
            X:864,
            Y:752
        },
        loginFacebookPassInput:{
            X:864,
            Y:887
        },
        loginFacebookEnterBtn:{
            X:864,
            Y:1022
        },
        signUp:{
            emailInput:{
                X:921,
                Y:461
            }
        },
        popupError:{
            ok:{
                X:936,
                Y:648
            }
        }
    },
    header:{
        home:{
           X:1652,
            Y:62
        },
        profileAvatar:{
            X:98,
            Y:68
        },
        cameraAvatar:{
            X:154,
            Y:434
        },
        editName:{
            X:480,
            Y:544
        },
        buyCoinButton:{
            X:862,
            Y:839
        },
        buyCrownButton:{
            X:524,
            Y:828
        },
        crownButton:{
            X:1333,
            Y:321
        },
        coinsButton:{
            X:644,
            Y:309
        },
        watchVideo:{
            X:438,
            Y:833
        },
        btnOKVideo:{
            X:879,
            Y:670
        },
        closedShop:{
            X:1674,
            Y:117
        },
        friendButton:{
            X:1755,
            Y:38
        },
        totalBetFriendButton:{
            X:1350,
            Y:220
        },
        coinsFriendButton:{
            X:902,
            Y:209
        },
        inboxFriendButton:{
            X:414,
            Y:213
        },
        closedFriends:{
            X:1681,
            Y:58
        },
        settingButtonClose:{
            X:1690,
            Y:98
        },
        settingButtonSevice:{
            X:454,
            Y:892
        },
        settingButtonPolicy:{
            X:946,
            Y:890
        },
        settingButton:{
            X:1849,
            Y:41
        },
        settingButtonVersion:{
            X:1528,
            Y:904
        },
        settingButtonCloseVersion:{
            X:1212,
            Y:400
        },
        settingButtonMusic:{
            X:1378,
            Y:324
        },
        settingButtonSound:{
            X:1372,
            Y:414
        },
        settingButtonLanguage:{
            X:1476,
            Y:510
        },
        settingButtonLanguage1:{
            X:1396,
            Y:578
        },
        settingButtonLanguage2:{
            X:1390,
            Y:654
        },
        settingButtonLanguage3:{
            X:1388,
            Y:714
        },
        settingButtonLanguage4:{
            X:1392,
            Y:784
        },
        settingButtonLanguage5:{
            X:1378,
            Y:860
        },
        settingButtonLanguage6:{
            X:1384,
            Y:930
        },
        settingButtonOKLanguage:{
            X:964,
            Y:670
        },
        popupShop:{
            X:777,
            Y:54
        },
        popupLeaderBoardFaceBook:{
            btnFriend:{
                X:418,
                Y:326
            },
            btnLeaderBoard:{
                X:400,
                Y:447
            },
            btnInvite:{
                X:932,
                Y:910
            },
            btnSendGift:{
                X:1267,
                Y:912
            },
           clickSendGift1:{
                X:1485,
                Y:274
            },
            clickSendGift2:{
                X:1485,
                Y:629
            },
            clickInvite:{
                X:1485,
                Y:629
            },
            btnAcceptAll:{
                X:1511,
                Y:925
            },
            btnOK:{
                X:953,
                Y:663
            },
            btnSend:{
                X:1371,
                Y:673
            },
            Invite:{
                X:1353,
                Y:167
            }
        }
    },
    body:{
        tutorial:{
            btnClaim:{
                X:950,
                Y:691
            },
            btnTutorialShop:{
                X:632,
                Y:56
            }
        },
        facebookBonusWheel:{
            btnSpin:{
                X:936,
                Y:461
            },
            btnCollectDailyWheel:{
                X:950,
                Y:778
            }
        },
        nezha:{
            X:553,
            Y:334
        },
        addTotalBet:{
            X:1235,
            Y:1009
        },
        subTotalBet:{
            X:929,
            Y:1000
        },
        spins:{
            X:1772,
            Y:516
        },
        btnInfo:{
            X:1757,
            Y:60
        },
        btnInfoBet:{
            X:712,
            Y:230
        },
        btnInfoInFo:{
            X:1261,
            Y:221
        },
        btnInfoAddPayLine:{
            X:574,
            Y:759
        },
        btnInfoSubPayLine:{
            X:854,
            Y:777
        },
        btnInfoAddBet:{
            X:1199,
            Y:774
        },
        btnInfoSubBet:{
            X:1483,
            Y:770
        },
        btnInfoClose:{
            X:1640,
            Y:74
        },
        deepblue:{
            X:950,
            Y:337
        },
        goldeneggs:{
            X:1299,
            Y:325
        },
        pharaoh:{
            X:1645,
            Y:293
        },
        boxing:{
            X:621,
            Y:710
        },
        romanEmpire:{
            X:938,
            Y:689
        }
    },
    footer:{
        achievementButton:{
            X:586,
            Y:1042
        },
        collectAchievementButton:{
            X:1510,
            Y:257
        },
        generalAchievementButton:{
            X:370,
            Y:400
        },
        gameAchievementButton:{
            X:402,
            Y:521
        },
        socialAchievementButton:{
            X:382,
            Y:661
        },
        coinCollectButton:{
            X:979,
            Y:985
        },
        closedAchievement:{
            X:1702,
            Y:46
        },
        giftButton:{
            X:1311,
            Y:1036
        },
        leaderboadButton:{
            X:418,
            Y:334
        },
        freecoingift:{
            X:972,
            Y:1020
        }
    },
    popup:{
        profile:{
             closeBtn:{
                 X:559,
                 Y:50
             },
            changeAvatarBtn:{
                X:169,
                Y:429
            },
            editNameBtn:{
                X:500,
                Y:530
            }
        },
        shop:{
            closeBtnShop:{
                X:1674,
                Y:120
            },
            closeError:{
                X:1366,
                Y:742
            }
        },
        comebackBonus:{
            collectBtn:{
                X:953,
                Y:796
            }
        },
        dailyBonusStreak:{
            collectBtn:{
                X:953,
                Y:883
            },
            closeBtn:{
                X:970,
                Y:613
            }
        },
        settings:{
            logOutBtn:{
                X:1346,
                Y:178
            },
            termOfServiceBtn:{
                X:562,
                Y:843
            },
            privacyPolicyBtn:{
                X:952,
                Y:824
            },
            closeBtn:{
                X:1611,
                Y:141
            }
        },
        btnOKChangeAvatar:{
            X:974,
            Y:676
        },
        editName: {
            btneditname:{
                X:956,
                Y:564
            },
            btnsendeditname:{
                X:1253,
                Y:695
            },
            btnOKeditname:{
                X:960,
                Y:677
            }
        },
        achievement:{
            btnGeneral:{
                X:386,
                Y:379
            },
            btnGame:{
                X:389,
                Y:527
            },
            btnSocial:{
                X:391,
                Y:645
            },
            btnCollectAch1:{
                X:1516,
                Y:248
            },
            btnCollectAch2:{
                X:1527,
                Y:395
            },
            btnCollectAch3:{
                X:1521,
                Y:549
            },
            btnCollectAch4:{
                X:1523,
                Y:776
            },
            btnCollectAch5:{
                X:1520,
                Y:810
            },
            btnCollectAch6:{
                X:1520,
                Y:964
            },
            btnCloseAch:{
                X:1700,
                Y:39
            }
        },
        btnComeBackBonus:{
            X:1107,
            Y:653
        },
        btnDailyBonusStreak:{
            X:1089,
            Y:902
        }
    }

};